### ISSUE TITLE
 Object #<Object> has no method 'emit'

### ISSUE THREAD

**Issue by kevinfoerster** [rwaldron/etherport#5]
hi,

i was playing around with my arduino ethernet and looked into etherport. it seems like its not working ootb as it throws this error:
```
/Users/kevin/Desktop/node_modules/etherport/lib/index.js:29
        this.emit("open");
             ^
TypeError: Object #<Object> has no method 'emit'
    at Object.EtherPort.state.flushTo (/Users/kevin/Desktop/node_modules/etherport/lib/index.js:29:14)
    at Server.<anonymous> (/Users/kevin/Desktop/node_modules/etherport/lib/index.js:42:11)
    at Server.emit (events.js:117:20)
    at TCP.onconnection (net.js:1192:8)
```

the code I used is fairly simple:

```
var EtherPort = require("etherport");
new EtherPort(8282) 
```

simply disabling the line in question in `etherport/lib/index.js:29` will *fix* this issue for now. i have no idea what this line of code is supposed to do, so this might not be the proper way to fix it.

**Comment by kevinfoerster** [comment]
oh, this was node v0.10.38 on a mac… not sure if it matters

**Comment by rwaldron** [comment]
Sorry I completely missed this! Turns out @soundanalogous ran into the same issue [here](https://github.com/rwaldron/johnny-five/issues/627#issuecomment-109172423)
