### ISSUE TITLE
Using Configurable firmata

### ISSUE THREAD

**Issue by finfort** [rwaldron/etherport#9]
![image](https://cloud.githubusercontent.com/assets/1012208/12817558/adb23fb8-cb63-11e5-9ba7-d4f75b5505f2.png)
Can i use ConfigurableFirmata with this configurations? from http://firmatabuilder.com/
I cant go In the Arduino IDE, open File -> Examples -> Firmata -> StandardFirmataEthernet
because it didn't work for some reason with ENC28J60. It's complicated without examples...
Can i merge https://github.com/ntruchsess/arduino_uip with StandardFirmataEthernet?

p.s I think if it'l will work that will be solution https://github.com/rwaldron/etherport/blob/master/eg/blink-firmata.js

**Comment by soundanalogous** [comment]
I have not had luck with the ENC28J60. At least one person has (the original author of the Firmata ethernet code). I think it depends on the particular shield but I don't know which one (or ones) actually work.

I dropped ENC28J60 support from StandardFirmataEthernet because I could never get it to work with my hardware, nor anyone else I had test it. arduino_uip is also consumes a lot more Flash and RAM than the standard Arduino Ethernet library.

**Comment by soundanalogous** [comment]
Also try the IPv4 address of your server rather than `server.local`

**Comment by finfort** [comment]
Thanks for answer, do you know is https://github.com/jgautier/firmata works with ENC28J60
this example specifically https://github.com/rwaldron/etherport/blob/master/eg/blink-firmata.js
And you consider to also try with ConfigurableFirmata + IPv4 + johnny-five etherport? While drop on arduino_uip. Because i really interested in programming arduino with ethernet and other devices from nodejs, where i can read about good and bad parts of nodejs(johnny-five, firmatajs) vs sketches(arduino code)

**Comment by soundanalogous** [comment]
I have never been able to get ENC28J60 to work with Firmata (either ConfigurableFirmata or StandardFirmataEthernet). The only ethernet shield that I know for certain works is the [Arduino Ethernet Shield](https://www.arduino.cc/en/Main/ArduinoEthernetShield). And this works with both ConfigurableFirmata and StandardFirmataEthernet. Other Wiznet W5100 based Ethernet shields may also work but I have not tested them (since I only have the Arduino Ethernet Shield). I need to add a disclaimer about ENC28J60.

WiFi was also recently added and the following two shields work with ConfigurableFirmata and StandardFirmataWiFi:
- [Arduino WiFi 101 shield](https://www.arduino.cc/en/Main/ArduinoWiFiShield101)
- [Arduino WiFi shield (legacy)](https://www.arduino.cc/en/Main/ArduinoWiFiShield)

Also the new [Arduino MRK1000](https://www.arduino.cc/en/Main/ArduinoMKR1000) will work with StandardFirmataWiFi and ConfigurableFirmata, but it has not yet been released:

**Comment by finfort** [comment]
@ntruchsess said here https://github.com/4ntoine/ArduinoCommander-ethernet/issues/1#issuecomment-27311757 that Configurable-firmata runs fine with my UIPEthernet-library for ENC28J60 and this guy @mcinnes01 had same issue as i https://github.com/firmata/arduino/issues/150#issuecomment-56904972 maybe i can contribute to ConfigurableFirmata to fully support nano v3 and an ENC28J60, where i need to start? 
For now this didn't work on nano v3 and an ENC28J60
And i want to connect like this https://github.com/finfort/ArduinoNanoRelay/blob/master/app/server/app.ts
``` c
#include <ConfigurableFirmata.h>

#include <UIPEthernet.h>
#include <EthernetClientStream.h>

EthernetClient client;

const byte mac[] = {0xDE, 0xAA, 0xBB, 0xCC, 0xDD, 0x01};
int remotePort = 3030;
IPAddress localIp(192, 168, 0, 150);
IPAddress remoteIp(192, 168, 0, 157);
EthernetClientStream stream(client, localIp, remoteIp, NULL, remotePort);

#include <DigitalInputFirmata.h>
DigitalInputFirmata digitalInput;

#include <DigitalOutputFirmata.h>
DigitalOutputFirmata digitalOutput;

#include <FirmataExt.h>
FirmataExt firmataExt;

void systemResetCallback()
{
  for (byte i = 0; i < TOTAL_PINS; i++) {
    if (IS_PIN_ANALOG(i)) {
    } else if (IS_PIN_DIGITAL(i)) {
      Firmata.setPinMode(i, OUTPUT);
    }
  }
  firmataExt.reset();
}

void setup()
{
  Ethernet.begin((uint8_t *)mac);
  Firmata.setFirmwareVersion(FIRMWARE_MAJOR_VERSION, FIRMWARE_MINOR_VERSION);

  firmataExt.addFeature(digitalInput);
  firmataExt.addFeature(digitalOutput);
  Firmata.attach(SYSTEM_RESET, systemResetCallback);

  for (byte i = 0; i < TOTAL_PINS; i++) {
    if (IS_PIN_SPI(i)
        || 4 == i
        || 10 == i
#if defined(__AVR_ATmega32U4__)
        || 24 == i
        || 28 == i
#endif
      ) {
      Firmata.setPinMode(i, PIN_MODE_IGNORE);
    }
  }

  pinMode(PIN_TO_DIGITAL(4), OUTPUT);
  digitalWrite(PIN_TO_DIGITAL(4), HIGH);

#if defined(__AVR_ATmega1280__) || defined(__AVR_ATmega2560__)
  pinMode(PIN_TO_DIGITAL(53), OUTPUT);
#endif

  Firmata.begin(stream);

  systemResetCallback();
}

void loop()
{
  digitalInput.report();

  while(Firmata.available()) {
    Firmata.processInput();
  }

}
```

**Comment by soundanalogous** [comment]
Like I said, I suspect that not all ENC28J60 modules will work. If you can find out exactly which module @ntruchsess used, then we would know at least one that does work. The likely cause for others not working is that they likely require other pins to be ignored. Look at the schematics for your module and ignore any pins that are wired to the arduino and unignore any that are not (see where `PIN_MODE_IGNORE` is used in your code above).

If that doesn't work, then I suggest digging into the UIPEthernet library since I'm certain the issue isn't in ConfigurableFirmata since it does work reliably with Wiznet Ethernet modules.

**Comment by finfort** [comment]
I got lucky with ConfigurableFirmata,  it's works  with  nano v3 and ENC28J60. Works with Firmata.js and etherport as well. One disadvantage that it uses lots of memory
https://github.com/firmata/ConfigurableFirmata/blob/master/examples/ConfigurableFirmata/ConfigurableFirmata.ino

**Comment by soundanalogous** [comment]
Can you post a link to the specific ENC28J60 module you are using so I can document it as one that is known to work?

> One disadvantage that it uses lots of memory

Yes, the UIPEthernet library uses a lot of memory

**Comment by finfort** [comment]
sure, http://www.amazon.com/uxcell%C2%AE-ENC28J60-Crystal-Ethernet-Network/dp/B00EDMNEIG/ref=sr_1_3?ie=UTF8&qid=1454870789&sr=8-3&keywords=ENC28J60

**Comment by soundanalogous** [comment]
Thanks! Also which pins on that board did you wire to the Nano?

**Comment by finfort** [comment]
| ENC28J60 Module | Arduino Nano v3 Board           | 
| ------------- |:-------------:| 
| LNT    |D2| 
| SO 	 |D12|   
| SCK	 |D13|    
| RST	 |RST|
| Q3	 |3V3|
| GND	 |GND|
| CS	 |D10|
| ST	 |D11|

![ethernet](https://cloud.githubusercontent.com/assets/1012208/12874816/d14ad33c-cdec-11e5-8fa1-972db8f38899.jpg)

**Comment by finfort** [comment]
``` c
#include "ConfigurableFirmata.h"
#include <UIPEthernet.h>

#if defined ethernet_h || defined UIPETHERNET_H || defined _YUN_CLIENT_H_
#define NETWORK_FIRMATA

#define remote_ip IPAddress(192, 168, 0, 102)
#define remote_port 3030
#define local_ip IPAddress(192, 168, 0, 6)
const byte mac[] = {0x90, 0xA2, 0xDA, 0x0D, 0x07, 0x02};
#endif


#include <DigitalInputFirmata.h>
DigitalInputFirmata digitalInput;

#include <DigitalOutputFirmata.h>
DigitalOutputFirmata digitalOutput;

#include <AnalogInputFirmata.h>
AnalogInputFirmata analogInput;

#include <AnalogOutputFirmata.h>
AnalogOutputFirmata analogOutput;

//#include <Servo.h>
//#include <ServoFirmata.h>
//ServoFirmata servo;
// ServoFirmata depends on AnalogOutputFirmata
#if defined ServoFirmata_h && ! defined AnalogOutputFirmata_h
#error AnalogOutputFirmata must be included to use ServoFirmata
#endif

//#include <Wire.h>
//#include <I2CFirmata.h>
//I2CFirmata i2c;
//
//#include <OneWireFirmata.h>
//OneWireFirmata oneWire;
//
//#include <StepperFirmata.h>
//StepperFirmata stepper;

#include <SerialFirmata.h>
SerialFirmata serial;

#include <FirmataExt.h>
FirmataExt firmataExt;

//#include <FirmataScheduler.h>
//FirmataScheduler scheduler;

// To add Encoder support you must first install the FirmataEncoder and Encoder libraries:
// https://github.com/firmata/FirmataEncoder
// https://www.pjrc.com/teensy/td_libs_Encoder.html
// #include <Encoder.h>
// #include <FirmataEncoder.h>
// FirmataEncoder encoder;

/*===================================================================================
 * END FEATURE CONFIGURATION - you should not need to change anything below this line
 *==================================================================================*/

// dependencies. Do not comment out the following lines
#if defined AnalogOutputFirmata_h || defined ServoFirmata_h
#include <AnalogWrite.h>
#endif

#if defined AnalogInputFirmata_h || defined I2CFirmata_h || defined FirmataEncoder_h
#include <FirmataReporting.h>
FirmataReporting reporting;
#endif

// dependencies for Network Firmata. Do not comment out.
#ifdef NETWORK_FIRMATA
#if defined remote_ip && defined remote_host
#error "cannot define both remote_ip and remote_host at the same time!"
#endif
#include <EthernetClientStream.h>
#ifdef _YUN_CLIENT_H_
YunClient client;
#else
EthernetClient client;
#endif
#if defined remote_ip && !defined remote_host
#ifdef local_ip
EthernetClientStream stream(client, local_ip, remote_ip, NULL, remote_port);
#else
EthernetClientStream stream(client, IPAddress(0, 0, 0, 0), remote_ip, NULL, remote_port);
#endif
#endif
#if !defined remote_ip && defined remote_host
#ifdef local_ip
EthernetClientStream stream(client, local_ip, IPAddress(0, 0, 0, 0), remote_host, remote_port);
#else
EthernetClientStream stream(client, IPAddress(0, 0, 0, 0), IPAddress(0, 0, 0, 0), remote_host, remote_port);
#endif
#endif
#endif

/*==============================================================================
 * FUNCTIONS
 *============================================================================*/

void systemResetCallback()
{
  // initialize a default state

  // pins with analog capability default to analog input
  // otherwise, pins default to digital output
  for (byte i = 0; i < TOTAL_PINS; i++) {
    if (IS_PIN_ANALOG(i)) {
#ifdef AnalogInputFirmata_h
      // turns off pull-up, configures everything
      Firmata.setPinMode(i, PIN_MODE_ANALOG);
#endif
    } else if (IS_PIN_DIGITAL(i)) {
#ifdef DigitalOutputFirmata_h
      // sets the output to 0, configures portConfigInputs
      Firmata.setPinMode(i, OUTPUT);
#endif
    }
  }

#ifdef FirmataExt_h
  firmataExt.reset();
#endif
}

/*==============================================================================
 * SETUP()
 *============================================================================*/

void setup()
{
  /*
   * ETHERNET SETUP
   */
#ifdef NETWORK_FIRMATA
#ifdef _YUN_CLIENT_H_
  Bridge.begin();
#else
#ifdef local_ip
  Ethernet.begin((uint8_t *)mac, local_ip); //start Ethernet
#else
  Ethernet.begin((uint8_t *)mac); //start Ethernet using dhcp
#endif
#endif
  delay(1000);
#endif

  /*
   * FIRMATA SETUP
   */
  Firmata.setFirmwareVersion(FIRMATA_FIRMWARE_MAJOR_VERSION, FIRMATA_FIRMWARE_MINOR_VERSION);

#ifdef FirmataExt_h
#ifdef DigitalInputFirmata_h
  firmataExt.addFeature(digitalInput);
#endif
#ifdef DigitalOutputFirmata_h
  firmataExt.addFeature(digitalOutput);
#endif
#ifdef AnalogInputFirmata_h
  firmataExt.addFeature(analogInput);
#endif
#ifdef AnalogOutputFirmata_h
  firmataExt.addFeature(analogOutput);
#endif
#ifdef ServoFirmata_h
  firmataExt.addFeature(servo);
#endif
#ifdef I2CFirmata_h
  firmataExt.addFeature(i2c);
#endif
#ifdef OneWireFirmata_h
  firmataExt.addFeature(oneWire);
#endif
#ifdef StepperFirmata_h
  firmataExt.addFeature(stepper);
#endif
#ifdef SerialFirmata_h
  firmataExt.addFeature(serial);
#endif
#ifdef FirmataReporting_h
  firmataExt.addFeature(reporting);
#endif
#ifdef FirmataScheduler_h
  firmataExt.addFeature(scheduler);
#endif
#ifdef FirmataEncoder_h
  firmataExt.addFeature(encoder);
#endif
#endif
  /* systemResetCallback is declared here (in ConfigurableFirmata.ino) */
  Firmata.attach(SYSTEM_RESET, systemResetCallback);

  // Network Firmata communicates with Ethernet-shields over SPI. Therefor all
  // SPI-pins must be set to PIN_MODE_IGNORE. Otherwise Firmata would break SPI-communication.
  // add Pin 10 and configure pin 53 as output if using a MEGA with Ethernetshield.
  // No need to ignore pin 10 on MEGA with ENC28J60, as here pin 53 should be connected to SS:
#ifdef NETWORK_FIRMATA

  #ifndef _YUN_CLIENT_H_
  // ignore SPI and pin 4 that is SS for SD-Card on Ethernet-shield
  for (byte i = 0; i < TOTAL_PINS; i++) {
    if (IS_PIN_SPI(i)
        || 4 == i  // SD Card on Ethernet shield uses pin 4 for SS
        || 10 == i // Ethernet-shield uses pin 10 for SS
       ) {
      Firmata.setPinMode(i, PIN_MODE_IGNORE);
    }
  }
  //  pinMode(PIN_TO_DIGITAL(53), OUTPUT); configure hardware-SS as output on MEGA
  pinMode(PIN_TO_DIGITAL(4), OUTPUT); // switch off SD-card bypassing Firmata
  digitalWrite(PIN_TO_DIGITAL(4), HIGH); // SS is active low;
  #endif

  #if defined(__AVR_ATmega1280__) || defined(__AVR_ATmega2560__)
    pinMode(PIN_TO_DIGITAL(53), OUTPUT); // configure hardware SS as output on MEGA
  #endif

  // start up Network Firmata:
  Firmata.begin(stream);
#else
  // Uncomment to save a couple of seconds by disabling the startup blink sequence.
  // Firmata.disableBlinkVersion();

  // start up the default Firmata using Serial interface:
  Firmata.begin(57600);
#endif
  systemResetCallback();  // reset to default config
}

/*==============================================================================
 * LOOP()
 *============================================================================*/
void loop()
{
#ifdef DigitalInputFirmata_h
  /* DIGITALREAD - as fast as possible, check for changes and output them to the
   * stream buffer using Firmata.write()  */
  digitalInput.report();
#endif

  /* STREAMREAD - processing incoming message as soon as possible, while still
   * checking digital inputs.  */
  while (Firmata.available()) {
    Firmata.processInput();
#ifdef FirmataScheduler_h
    if (!Firmata.isParsingMessage()) {
      goto runtasks;
    }
  }
  if (!Firmata.isParsingMessage()) {
runtasks: scheduler.runTasks();
#endif
  }

  /* SEND STREAM WRITE BUFFER - TO DO: make sure that the stream buffer doesn't go over
   * 60 bytes. use a timer to sending an event character every 4 ms to
   * trigger the buffer to dump. */

#ifdef FirmataReporting_h
  if (reporting.elapsed()) {
#ifdef AnalogInputFirmata_h
    /* ANALOGREAD - do all analogReads() at the configured sampling interval */
    analogInput.report();
#endif
#ifdef I2CFirmata_h
    // report i2c data for all device with read continuous mode enabled
    i2c.report();
#endif
#ifdef FirmataEncoder_h
    // report encoders positions if reporting enabled.
    encoder.report();
#endif
  }
#endif
#ifdef StepperFirmata_h
  stepper.update();
#endif
#ifdef SerialFirmata_h
  serial.update();
#endif

#if defined NETWORK_FIRMATA && !defined local_ip &&!defined _YUN_CLIENT_H_
  // only necessary when using DHCP, ensures local IP is updated appropriately if it changes
  if (Ethernet.maintain()) {
    stream.maintain(Ethernet.localIP());
  }
#endif
}
```

**Comment by soundanalogous** [comment]
I was also able to get it to work with my ENC28J60 shield. I now have a better understanding of some of the potential issues:

- If an ENC28J60 shield (there are shield varieties and breakout board varieties) does not bridge the ICSP pins to the attached board, it will not work (Mega, Leonardo, etc)
  - Users should buy the breakout board variety since it can be used with a wider range of boards - especially boards with more memory such as an Arduino Mega.
- The UIPEthernet does not fully support non-AVR boards. I need to verify exactly which boards it works with. I suspect the Arduino Due, but likely no other SAM or SAMD boards without changes.
- The UIPEthernet library consumes a lot of memory. When using an Arduino Uno, a user can only enable digital and analog I/O for the board and no additional Firmata features. Even with this limited set of features, only 264 bytes of SRAM are available for local variables when using an Uno. Adding an additional feature or two may still compile, but it may not upload due to the space required on the board for the bootloader.

I'll update the ConfigurableFirmata README with this info.

**Comment by soundanalogous** [comment]
Thanks @finfort for your help in debugging this issue.
